# SpvToHeader.cmake
#
# Converts a SPIR-V binary (.spv) into a C++ header that embeds the bytecode
# as a constexpr uint32_t array, ready to pass to VkShaderModuleCreateInfo.
#
# Usage (from CMake add_custom_command):
#   cmake -DINPUT=<path/to/shader.spv>
#         -DOUTPUT=<path/to/output.h>
#         -DVAR_NAME=<C++ variable name>
#         -P SpvToHeader.cmake

cmake_minimum_required(VERSION 3.20)

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT OR NOT DEFINED VAR_NAME)
    message(FATAL_ERROR
        "SpvToHeader.cmake: required variables INPUT, OUTPUT, and VAR_NAME must be defined.\n"
        "Example: cmake -DINPUT=shader.spv -DOUTPUT=shader_spv.h -DVAR_NAME=kShaderSpv -P SpvToHeader.cmake")
endif()

# Read the .spv binary as a flat lowercase hex string (2 chars per byte, LE byte order on disk).
file(READ "${INPUT}" BYTES HEX)
string(LENGTH "${BYTES}" HEX_LEN)

if(HEX_LEN EQUAL 0)
    message(FATAL_ERROR "SpvToHeader.cmake: INPUT file '${INPUT}' is empty.")
endif()

math(EXPR REMAINDER "${HEX_LEN} % 8")
if(NOT REMAINDER EQUAL 0)
    message(FATAL_ERROR
        "SpvToHeader.cmake: INPUT '${INPUT}' byte count is not a multiple of 4 (not valid SPIR-V).")
endif()

math(EXPR UINT32_COUNT "${HEX_LEN} / 8")

# Build the array body.
# Each group of 8 hex chars encodes one uint32_t stored in little-endian byte order on disk.
# E.g. SPIR-V magic 0x07230203 is stored as bytes 03 02 23 07.
# The flat hex string therefore reads "03022307" for that word.
# We reconstruct the uint32_t value by reversing the byte order:
#   B0=hex[0..1], B1=hex[2..3], B2=hex[4..5], B3=hex[6..7]  → 0xB3B2B1B0
set(ARRAY_BODY "")
set(i 0)
while(i LESS ${UINT32_COUNT})
    math(EXPR OFFSET "${i} * 8")
    string(SUBSTRING "${BYTES}" ${OFFSET} 8 CHUNK)

    string(SUBSTRING "${CHUNK}" 0 2 B0)
    string(SUBSTRING "${CHUNK}" 2 2 B1)
    string(SUBSTRING "${CHUNK}" 4 2 B2)
    string(SUBSTRING "${CHUNK}" 6 2 B3)

    string(APPEND ARRAY_BODY "0x${B3}${B2}${B1}${B0}u,")

    math(EXPR i "${i} + 1")
endwhile()

# Strip trailing comma for cleanliness.
string(REGEX REPLACE ",$" "" ARRAY_BODY "${ARRAY_BODY}")

set(HEADER_CONTENT
"#pragma once
// Auto-generated by SpvToHeader.cmake — do not edit.
// Source: ${INPUT}
#include <cstdint>

// clang-format off
static constexpr uint32_t ${VAR_NAME}[] = { ${ARRAY_BODY} };
static constexpr uint32_t ${VAR_NAME}Size = sizeof(${VAR_NAME});
// clang-format on
")

file(WRITE "${OUTPUT}" "${HEADER_CONTENT}")
message(STATUS "SpvToHeader: wrote ${UINT32_COUNT} uint32_t words to '${OUTPUT}'")
