#pragma once

namespace BECore {

    /**
     * @brief Traits struct linking a factory base type to its generated factory
     *
     * The primary template is intentionally left undefined.
     * Specializations are auto-generated by the meta-generator in EnumXxx.gen.hpp
     * for every type marked with BE_CLASS(Name, FACTORY_BASE).
     *
     * @tparam T The factory base type (e.g., ILogSink, IAssertHandler)
     *
     * @example Generated specialization:
     * @code
     * template<>
     * struct FactoryTraits<ILogSink> {
     *     using FactoryType = LogSinkFactory;
     *     using EnumType    = LogSinkType;
     *     static constexpr eastl::string_view elementName = "sink";
     * };
     * @endcode
     */
    template <typename T>
    struct FactoryTraits;

    /**
     * @brief Concept that detects whether a type has a generated factory
     *
     * Satisfied when FactoryTraits<T> is specialised with FactoryType,
     * EnumType, and elementName members.
     */
    template <typename T>
    concept HasFactory = requires {
        typename FactoryTraits<T>::FactoryType;
        typename FactoryTraits<T>::EnumType;
        {
            FactoryTraits<T>::elementName
        } -> std::convertible_to<eastl::string_view>;
    };

}  // namespace BECore
